# netlify.toml

[build]
  # The directory where your serverless functions are located.
  functions = "netlify/functions/"
  # The directory that contains your static assets to be published.
  publish = "public/"

# This is a specific rewrite rule for the API.
# It proxies any request starting with /api/ to your server function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200