# netlify.toml

[build]
  functions = "netlify/functions/"
  publish = "public/"

# This rule says: any URL that is not a file in the `public` directory
# should be handled by the `server` function.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = false