# Netlify configuration file

[build]
  # The directory where your serverless functions are located.
  functions = "netlify/functions/"
  # The directory that contains your static assets (HTML, JS, CSS).
  publish = "public/"

# Redirect all traffic to our serverless Express function.
# This is the "magic" that makes the Express app work.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200